### ISSUE TITLE
Ets problem with Xmerl "Too many db tables"

### ISSUE THREAD

**Issue by mpneuried** [kbrw/sweet_xml#41] opened 2017-01-12 05:59 UTC
```
** (SystemLimitError) a system limit has been reached
    (stdlib) :ets.new(:rules, [:set, :public])
    (xmerl) xmerl_scan.erl:418: :xmerl_scan.initial_state/2
    (xmerl) xmerl_scan.erl:300: :xmerl_scan.int_string/4
    (xmerl) xmerl_scan.erl:291: :xmerl_scan.string/2
    (sweet_xml) lib/sweet_xml.ex:233: SweetXml.parse/2
    (sweet_xml) lib/sweet_xml.ex:421: SweetXml.xpath/2
    (sweet_xml) lib/sweet_xml.ex:454: SweetXml.xpath/3
    (ex_aws) lib/ex_aws/sqs/parsers.ex:99: ExAws.SQS.Parsers.parse/2
10:22:19.693 [error] ** Too many db tables **
```

Probably this [link](http://erlang.org/pipermail/erlang-questions/2005-October/017416.html) provides a solution?

Or is this a problem within the usage by [ExAws](https://github.com/CargoSense/ex_aws)?

**Comment by mguilmineau** [comment] 2022-03-28 23:14
See elixir forum post https://elixirforum.com/t/creeping-ets-tables/46817/5 

I believe this is caused by a lack of :ets table cleanup on xmerl_scan crash.

You can reproduce this by running an invalid scan, as follows:

import SweetXml
result = "hello" |> xpath(~x"//matchup/name/text()")
result = "hello" |> xpath(~x"//matchup/name/text()")
:ets.i

And you'll see the 
 #Ref<0.2464904680.2561015810.133724> rules             set   0      309      <0.2323.0>
 #Ref<0.2464904680.2563112961.216946> rules             set   0      309      <0.2323.0>
accumulating at the bottom of the info output.

This :ets table is created on xmler_scan init,:
initial_state([], S=#xmerl_scanner{rules = undefined}) ->
    Tab = ets:new(rules, [set, public]),
    S#xmerl_scanner{rules = Tab};

and does not get cleaned up on crash. 

There is a limit on how many :ets table the VM supports so eventually this "leak" causes an actual crash.

Not sure if you can call cleanup in sweet_xml on crash or if this must be handled within xmerl_scan only.

cleanup(S=#xmerl_scanner{keep_rules = false,
			 rules = Rules}) ->
    ets:delete(Rules),
    S#xmerl_scanner{rules = undefined};

**Comment by Shakadak** [comment] 2022-03-29 14:54
Hey,

thanks for bringing that up.

There is one thing I don't understand, if I use `SweetXml.parse("hello")` (which is equivalent to your example) repeatedly in IEx, the ets tables accumulate, but if I wrap it in a spawn_link, the fresh process and IEx crashes accordingly, and the ets is removed. So there must be something over sweet_xml, maybe ex_aws, maybe your code, that prevent the process handling the parsing from dying. But that's fine.

`:xmerl_scan.cleanup/1` is not exported so we cannot use it ourselves, but we can do something similar ourselves.
As a temporary fix until we publish something, you can handle the ets for the rules on your own. For exemple:
```elixir
tid = :ets.new(:xmerl_rules, [:public]) # It's not actually named because it would prevent concurrent use of the same code
try do
  SweetXml.parse("hello", rules: tid)
after
  :ets.delete(tid)
end
```

This made me realize that the handling of the `:dtd` option was made poorly as it can easily be overridden if someone passes the option `{:rules, read_fun, write_fun, state_container}`. :\
Note that using the dtd options `:none` or `[only: _]` still needs the above code as xmerl_scan places `{:rules, state_container}` and `{:rules, _, _, state_container}` in two different place in its scan structure.

**Comment by mguilmineau** [comment] 2022-03-29 21:51
Regarding spawn_link in iex: that is just how iex works. If you wrap your command with spawn_link and that command throws an exit, parent process iex will exit as well and restart and all the :ets tabled are cleared, whereas if you don't wrap with spawn_link, iex reports an exit but does not exit itself and does not reset its :ets tables. 
Demonstration below:

>iex
Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> self()
#PID<0.104.0>
iex(2)> exit("hello")
** (exit) "hello"

iex(2)> self()
#PID<0.104.0>
iex(3)> spawn_link( fn -> exit("hello") end )
** (EXIT from #PID<0.104.0>) shell process exited with reason: "hello"

Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> self()
#PID<0.110.0>

The thing is :ets tables are shared among processes and I don't really want to bring down my entire application just because an XML command from ex_aws is corrupted.
As for your workaround it would need to be implemented within the ex_aws library. I will let them know of this issue. 
Another temporary workaround is to increase the max :ets tables allowed in the erl VM...

**Comment by Shakadak** [comment] 2022-03-30 10:10
Yes, I was mostly curious about where does the exit get caught, if it's within ex_aws that's unfortunate, but otherwise you also have the possibility of using `spawn_monitor` to get the automatic cleanup in case of exit, and a message to know it failed.

Anyway, I'll try to fix the problem as soon as possible, and if it's not urgent, I'd like to improve at the same time the handling of the xmerl `:rules` options when mixed with sweet_xml `:dtd` options before publishing. As it is partially linked.

**Comment by mguilmineau** [comment] 2022-03-30 16:00
It's not urgent.

I catch the exit when getting an S3 object so as to smoothly reattempt:
	catch
		#  {:fatal, {:expected_element_start_tag, {:file, :file_name_unknown}, {:line, 1}, {:col, 1}}}
		:exit, {:fatal, {:expected_element_start_tag, {:file, :file_name_unknown}, _line, _col}} -> nil
		#  {:fatal, {:unexpected_end, {:file, :file_name_unknown}, {:line, 2}, {:col, 16843}}}
		:exit, {:fatal, {:unexpected_end, {:file, :file_name_unknown}, _line, _col}} -> nil
		#  {:fatal, {{:endtag_does_not_match, {:was, :Las, :should_have_been, :LastModified}}, {:file, :file_name_unknown}, {:line, 2}, {:col, 287054}}}}}
		:exit, {:fatal, {{:endtag_does_not_match, _was_x_should_have_been_y}, {:file, :file_name_unknown}, _line, _col}} -> nil

I can use spawn_monitor in the meantime, as you suggest.

**Comment by Shakadak** [comment] 2022-04-11 10:38
v0.7.3 is published on hex.pm, I'll close this issue later

**Comment by mguilmineau** [comment] 2022-04-21 03:25
Looks good to me. :)

**Closed** 2022-05-24 15:29 UTC
